name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Verilator dependencies
        run: |
            sudo apt-get install -y \
                git help2man perl python3 make \
                g++ \
                libfl2 \
                libfl-dev \
                zlibc zlib1g zlib1g-dev \
                git autoconf flex bison

      - name: Clone Verilator
        run: git clone https://github.com/verilator/verilator $HOME/verilator

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Set up testing environment
        run: pip install -r test/requirements.txt

      - name: Run tests
        run: |
          source Setup.bsh
          cd test
          pytest
